### ISSUE TITLE
[SUGGESTION] Make the Env_projectedtexture acts like to Portal 2's system

### ISSUE THREAD

**Issue by xXxToxicBlueDustxXx** [Demez/Half-Life-2-Revamped#2]
in Portal 2 the env_projectedsystem is heavy modified if you play Portal 2 you can see the difference

**Comment by Demez** [comment]
The only way i can think of making it closest to that is to backport the ASW projected texture and some of the modifications to it from Enhanced Source, which im pretty sure is beyond what im able to do I will still give it a shot though.

**Comment by xXxToxicBlueDustxXx** [comment]
i see the commit but i don´t sure but:

- you need to modified the ClientSide and Serveside of Env_ProjectedTexture
- modified the clientshadowsmgr.cpp ( you need firs apply the Shadosw RTT from Alien Swarm ( see the VDC ) and the env_project texture fixes ( i don't know if this is need )

**Comment by Demez** [comment]
pretty much already taken care of when i moved to ASW
